Settings:
  #Set to '' for no permission.
  permission: ''
  server: "Hub"
  commands:
    - hub
    - leave
Messages:
  send: "&aYou were send to the hub."
  no-permission: "&cYou can't do that"
  server-offline: "&cSorry, but server is off."